version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    container_name: php_app
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    env_file:
      - .env
    networks:
      - appnet

  db:
    image: mysql:8.0
    container_name: match_making_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE:     ${DB_NAME}
      MYSQL_USER:         ${DB_USER}
      MYSQL_PASSWORD:     ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/Deploy_database/database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql:ro
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: match_making_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - appnet

volumes:
  db_data:
  redis_data:

networks:
  appnet:
    driver: bridge